const KEY='ams-v2.1-demo';
const data=JSON.parse(localStorage.getItem(KEY)||'null')||{assets:[{id:'a1',type:'countable',code:'EQ-0001',name:'ช้อนโต๊ะ',category:'Cutlery',date:'2022-06-30',price:25,qty:300,unit:'คัน',serial:'',location:'Restaurant',owner:'F&B',warranty:'',custom:[{k:'วัสดุ',v:'Stainless'}]},{id:'a2',type:'individual',code:'AST-0002',name:'ตู้ทำน้ำแข็ง',category:'Kitchen Equipment',date:'2024-01-15',price:85000,qty:1,unit:'เครื่อง',serial:'ICE-88921',location:'Main Kitchen',owner:'Kitchen',warranty:'2027-01-15',custom:[{k:'PM',v:'ทุก 3 เดือน'},{k:'เปลี่ยนไส้กรอง',v:'ทุก 6 เดือน'}]},{id:'a3',type:'individual',code:'AST-0003',name:'แอร์ Lobby',category:'Air Conditioner',date:'2025-03-01',price:42000,qty:1,unit:'เครื่อง',serial:'AC-22001',location:'Lobby',owner:'Engineering',warranty:'2028-03-01',custom:[{k:'PM',v:'ทุก 3 เดือน'}]}],counts:[{id:'c1',assetId:'a1',date:'2022-08-30',expected:300,actual:250,note:'ตรวจนับประจำรอบ'}],events:[{id:'e1',assetId:'a2',kind:'PM',date:'2026-07-01',qty:1,reason:'PM ตามรอบ',note:'ตรวจเช็กระบบและทำความสะอาด'}],writeoffs:[],reminders:[{id:'r1',assetId:'a2',title:'เปลี่ยนไส้กรอง',due:'2027-01-10',repeat:'ทุก 6 เดือน',lead:30,status:'active'},{id:'r2',assetId:'a3',title:'PM',due:'2026-09-01',repeat:'ทุก 3 เดือน',lead:15,status:'active'}],assignments:[{id:'as1',assignee:'Captain A',role:'Captain',scopeType:'พื้นที่/แผนก',scope:'Restaurant',task:'ดูแลตรวจนับและ Spoil',from:'2026-07-01',to:''}]};
const $=id=>document.getElementById(id),save=()=>localStorage.setItem(KEY,JSON.stringify(data)),asset=id=>data.assets.find(a=>a.id===id),empty=t=>`<div class="empty">${t}</div>`;
const money=n=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(Number(n||0));
const fmtDate=s=>s?new Date(s+'T00:00:00').toLocaleDateString('th-TH',{day:'2-digit',month:'short',year:'numeric'}):'-';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const titles={dashboard:['แดชบอร์ด','ภาพรวมระบบบริหารจัดการทรัพย์สิน'],assets:['ทรัพย์สิน','ทรัพย์สินรายชิ้นและอุปกรณ์นับจำนวน'],counts:['การตรวจนับ','ดูครั้งล่าสุดและส่วนต่าง'],events:['ชำรุด / Spoil','เหตุการณ์ชำรุด ซ่อม PM และหลักฐาน'],writeoff:['ตัดจำหน่าย / Write-off','รายงานตัดจำหน่ายสะสม'],reminders:['การแจ้งเตือน','กำหนดสิ่งที่อยากให้ระบบเตือนเอง'],tasks:['งานของฉัน','งานที่ได้รับมอบหมาย'],users:['ผู้ใช้งานและสิทธิ์','Role และ Assignment']};
function show(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v+'View').classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('pageTitle').textContent=titles[v][0];$('pageSub').textContent=titles[v][1];closeMenu();render()}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>show(n.dataset.view));$('menuBtn').onclick=()=>{$('sidebar').classList.add('open');$('overlay').classList.add('show')};$('overlay').onclick=closeMenu;function closeMenu(){$('sidebar').classList.remove('open');$('overlay').classList.remove('show')}
function summary(){const now=new Date(),soon=new Date(now.getTime()+30*864e5),total=data.assets.length,value=data.assets.reduce((s,a)=>s+(+a.price||0)*(+a.qty||1),0),damaged=data.events.filter(e=>e.kind.includes('Spoil')||e.kind.includes('ชำรุด')).length,repair=data.events.filter(e=>e.kind.includes('Repair')||e.kind.includes('ซ่อม')).length,never=data.assets.filter(a=>a.type==='countable'&&!data.counts.some(c=>c.assetId===a.id)).length,diff=data.counts.filter(c=>c.actual!==c.expected).length,due=data.reminders.filter(r=>r.status==='active'&&new Date(r.due)<=soon).length;const cards=[['ทรัพย์สินทั้งหมด',total,'รายการ','assets',''],['มูลค่ารวม',money(value),'ราคาซื้อสะสม','assets',''],['ใกล้ถึงกำหนด',due,'ภายใน 30 วัน','reminders','warn'],['Write-off สะสม',data.writeoffs.length,'รายการ','writeoff','danger'],['ชำรุด / Spoil',damaged,'เหตุการณ์','events','danger'],['กำลังซ่อม',repair,'เหตุการณ์','events','warn'],['ยังไม่เคยตรวจนับ',never,'รายการ','counts','warn'],['พบส่วนต่าง',diff,'รอบตรวจนับ','counts','danger']];$('summaryCards').innerHTML=cards.map(([t,v,s,target,cls])=>`<button class="summary-card clickable ${cls}" data-target="${target}"><span>${t}</span><strong>${v}</strong><small>${s}</small></button>`).join('');document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>show(b.dataset.target))}
function render(){summary();renderDashboard();renderAssets();renderCounts();renderEvents();renderWriteoffs();renderReminders();renderTasks();renderAssignments()}
function renderDashboard(){const rs=data.reminders.slice().sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5);$('dashReminders').innerHTML=rs.length?rs.map(reminderRow).join(''):empty('ยังไม่มี Reminder');const act=[...data.events.map(x=>({...x,t:'e'})),...data.writeoffs.map(x=>({...x,t:'w'})),...data.counts.map(x=>({...x,t:'c'}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,6);$('dashActivity').innerHTML=act.length?act.map(activityRow).join(''):empty('ยังไม่มีกิจกรรม')}
function renderAssets(){const q=$('searchAsset').value.toLowerCase(),type=$('filterType').value;const arr=data.assets.filter(a=>(!type||a.type===type)&&[a.code,a.name,a.category,a.location,a.owner].join(' ').toLowerCase().includes(q));$('assetList').innerHTML=arr.length?arr.map(a=>{const last=data.counts.filter(c=>c.assetId===a.id).sort((x,y)=>y.date.localeCompare(x.date))[0];const status=a.type==='countable'?(last?`ตรวจล่าสุด ${fmtDate(last.date)} · ส่วนต่าง ${last.actual-last.expected}`:'ยังไม่เคยตรวจนับ'):`Serial ${esc(a.serial||'-')}`;return `<div class="row"><div><h4>${esc(a.name)} <span class="pill ${a.type==='countable'?'blue':'green'}">${a.type==='countable'?'อุปกรณ์นับจำนวน':'ทรัพย์สินรายชิ้น'}</span></h4><div class="meta"><span>${esc(a.code)}</span><span>${esc(a.category)}</span><span>${esc(a.location)}</span><span>${status}</span></div></div><div><button class="secondary" onclick="editAsset('${a.id}')">แก้ไข</button></div></div>`}).join(''):empty('ไม่พบรายการ')}
$('searchAsset').oninput=renderAssets;$('filterType').onchange=renderAssets;
function renderCounts(){const arr=data.assets.filter(a=>a.type==='countable');$('countList').innerHTML=arr.length?arr.map(a=>{const c=data.counts.filter(x=>x.assetId===a.id).sort((x,y)=>y.date.localeCompare(x.date))[0];const text=c?`ตรวจล่าสุด ${fmtDate(c.date)} · ควรมี ${c.expected} · นับจริง ${c.actual} · ส่วนต่าง ${c.actual-c.expected}`:'ยังไม่เคยตรวจนับ';return `<div class="row"><div><h4>${esc(a.name)}</h4><div class="meta"><span>รับเข้า ${a.qty} ${esc(a.unit)}</span><span>${text}</span></div></div><div><button class="primary" onclick="addCount('${a.id}')">+ ตรวจนับ</button></div></div>`}).join(''):empty('ยังไม่มีอุปกรณ์นับจำนวน')}
function renderEvents(){$('eventList').innerHTML=data.events.length?data.events.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<div class="row"><div><h4>${esc(e.kind)} · ${esc(asset(e.assetId)?.name||'')}</h4><div class="meta"><span>${fmtDate(e.date)}</span><span>จำนวน ${e.qty}</span><span>${esc(e.reason)}</span><span>${esc(e.note||'')}</span></div></div></div>`).join(''):empty('ยังไม่มีเหตุการณ์')}
function renderWriteoffs(){$('woCount').textContent=data.writeoffs.length;$('woValue').textContent=money(data.writeoffs.reduce((s,w)=>s+(+w.value||0),0));$('writeoffList').innerHTML=data.writeoffs.length?data.writeoffs.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(w=>`<div class="row"><div><h4>${esc(asset(w.assetId)?.name||'')} · ${esc(asset(w.assetId)?.code||'')}</h4><div class="meta"><span>${fmtDate(w.date)}</span><span>จำนวน ${w.qty}</span><span>${esc(w.reason)}</span><span>${money(w.value)}</span></div></div></div>`).join(''):empty('ยังไม่มี Write-off')}
function renderReminders(){$('reminderList').innerHTML=data.reminders.length?data.reminders.slice().sort((a,b)=>a.due.localeCompare(b.due)).map(reminderRow).join(''):empty('ยังไม่มี Reminder')}
function reminderRow(r){const d=Math.ceil((new Date(r.due)-new Date())/864e5),cls=d<0?'red':d<=30?'orange':'green';return `<div class="row"><div><h4>${esc(r.title)} · ${esc(asset(r.assetId)?.name||'')}</h4><div class="meta"><span class="pill ${cls}">${d<0?'เกินกำหนด '+Math.abs(d)+' วัน':'เหลือ '+d+' วัน'}</span><span>${fmtDate(r.due)}</span><span>${esc(r.repeat)}</span><span>เตือนล่วงหน้า ${r.lead} วัน</span></div></div><div><button class="secondary" onclick="completeReminder('${r.id}')">ดำเนินการแล้ว</button></div></div>`}
function activityRow(x){if(x.t==='c')return `<div class="row"><div><h4>ตรวจนับ · ${esc(asset(x.assetId)?.name||'')}</h4><div class="meta"><span>${fmtDate(x.date)}</span><span>ส่วนต่าง ${x.actual-x.expected}</span></div></div></div>`;if(x.t==='w')return `<div class="row"><div><h4>Write-off · ${esc(asset(x.assetId)?.name||'')}</h4><div class="meta"><span>${fmtDate(x.date)}</span><span>${esc(x.reason)}</span></div></div></div>`;return `<div class="row"><div><h4>${esc(x.kind)} · ${esc(asset(x.assetId)?.name||'')}</h4><div class="meta"><span>${fmtDate(x.date)}</span><span>${esc(x.reason)}</span></div></div></div>`}
function renderTasks(){$('taskList').innerHTML=data.assignments.length?data.assignments.map(a=>`<div class="row"><div><h4>${esc(a.task)}</h4><div class="meta"><span>ผู้รับผิดชอบ ${esc(a.assignee)}</span><span>${esc(a.scopeType)}: ${esc(a.scope)}</span></div></div></div>`).join(''):empty('ยังไม่มีงาน')}
function renderAssignments(){$('assignList').innerHTML=data.assignments.length?data.assignments.map(a=>`<div class="row"><div><h4>${esc(a.assignee)} · ${esc(a.role)}</h4><div class="meta"><span>${esc(a.scopeType)}: ${esc(a.scope)}</span><span>${esc(a.task)}</span><span>เริ่ม ${fmtDate(a.from)}</span></div></div></div>`).join(''):empty('ยังไม่มีการมอบหมาย')}
$('addAssetQuick').onclick=$('addAssetBtn').onclick=()=>openAsset();
function openAsset(id=''){const a=id?asset(id):null;$('assetForm').reset();$('assetId').value=id;$('assetFormTitle').textContent=id?'แก้ไขทรัพย์สิน':'เพิ่มทรัพย์สิน';$('customFields').innerHTML='';if(a){$('assetType').value=a.type;$('assetCode').value=a.code;$('assetName').value=a.name;$('assetCategory').value=a.category;$('assetDate').value=a.date;$('assetPrice').value=a.price;$('assetQty').value=a.qty;$('assetUnit').value=a.unit;$('assetSerial').value=a.serial;$('assetLocation').value=a.location;$('assetOwner').value=a.owner;$('assetWarranty').value=a.warranty;(a.custom||[]).forEach(c=>addCustom(c.k,c.v))}$('assetDialog').showModal()}
window.editAsset=openAsset;$('addCustomField').onclick=()=>addCustom('','');function addCustom(k,v){const row=document.createElement('div');row.className='custom-row';row.innerHTML=`<input class="ck" placeholder="หัวข้อ เช่น PM / ไส้กรอง" value="${esc(k)}"><input class="cv" placeholder="รายละเอียด" value="${esc(v)}"><button type="button" class="danger-btn">ลบ</button>`;row.querySelector('button').onclick=()=>row.remove();$('customFields').appendChild(row)}
$('assetForm').onsubmit=e=>{e.preventDefault();const id=$('assetId').value||crypto.randomUUID();const obj={id,type:$('assetType').value,code:$('assetCode').value,name:$('assetName').value,category:$('assetCategory').value,date:$('assetDate').value,price:+$('assetPrice').value||0,qty:+$('assetQty').value||1,unit:$('assetUnit').value||'ชิ้น',serial:$('assetSerial').value,location:$('assetLocation').value,owner:$('assetOwner').value,warranty:$('assetWarranty').value,custom:[...document.querySelectorAll('.custom-row')].map(r=>({k:r.querySelector('.ck').value,v:r.querySelector('.cv').value})).filter(x=>x.k)};const i=data.assets.findIndex(x=>x.id===id);if(i>=0)data.assets[i]=obj;else data.assets.push(obj);save();$('assetDialog').close();render()};document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>$('assetDialog').close());
function generic(title,body,handler){$('genericTitle').textContent=title;$('genericBody').innerHTML=body;$('genericDialog').showModal();$('genericForm').onsubmit=e=>{e.preventDefault();handler(new FormData($('genericForm')));save();$('genericDialog').close();render()}}
document.querySelectorAll('.close-generic').forEach(b=>b.onclick=()=>$('genericDialog').close());
window.addCount=id=>generic('บันทึกการตรวจนับ',`<div class="form-grid"><label class="field">วันที่<input name="date" type="date" required></label><label class="field">ยอดคาดหมาย<input name="expected" type="number" required></label><label class="field">นับจริง<input name="actual" type="number" required></label><label class="field">หมายเหตุ<input name="note"></label></div>`,fd=>data.counts.push({id:crypto.randomUUID(),assetId:id,date:fd.get('date'),expected:+fd.get('expected'),actual:+fd.get('actual'),note:fd.get('note')}));
$('addEventBtn').onclick=()=>generic('บันทึกชำรุด / Spoil / Repair / PM',`<div class="form-grid"><label class="field">ทรัพย์สิน<select name="assetId">${data.assets.map(a=>`<option value="${a.id}">${esc(a.code)} · ${esc(a.name)}</option>`).join('')}</select></label><label class="field">ประเภท<select name="kind"><option>Spoil / ชำรุด</option><option>Repair / ซ่อม</option><option>PM</option><option>เปลี่ยนไส้กรอง</option><option>อื่นๆ</option></select></label><label class="field">วันที่<input name="date" type="date" required></label><label class="field">จำนวน<input name="qty" type="number" value="1"></label><label class="field">สาเหตุ<input name="reason" required></label><label class="field">รายละเอียด<input name="note"></label></div>`,fd=>data.events.push({id:crypto.randomUUID(),assetId:fd.get('assetId'),kind:fd.get('kind'),date:fd.get('date'),qty:+fd.get('qty'),reason:fd.get('reason'),note:fd.get('note')}));
$('addWriteoffBtn').onclick=()=>generic('Write-off / ตัดจำหน่าย',`<div class="form-grid"><label class="field">ทรัพย์สิน<select name="assetId">${data.assets.map(a=>`<option value="${a.id}">${esc(a.code)} · ${esc(a.name)}</option>`).join('')}</select></label><label class="field">วันที่<input name="date" type="date" required></label><label class="field">จำนวน<input name="qty" type="number" value="1"></label><label class="field">เหตุผล<select name="reason"><option>ชำรุดซ่อมไม่ได้</option><option>ซ่อมไม่คุ้ม</option><option>สูญหาย</option><option>หมดอายุการใช้งาน</option><option>ขายออก</option><option>บริจาค</option><option>ทำลาย</option><option>อื่นๆ</option></select></label><label class="field">มูลค่า<input name="value" type="number"></label></div>`,fd=>data.writeoffs.push({id:crypto.randomUUID(),assetId:fd.get('assetId'),date:fd.get('date'),qty:+fd.get('qty'),reason:fd.get('reason'),value:+fd.get('value')||0}));
$('addReminderBtn').onclick=()=>generic('เพิ่มการแจ้งเตือน',`<div class="form-grid"><label class="field">ทรัพย์สิน<select name="assetId">${data.assets.map(a=>`<option value="${a.id}">${esc(a.code)} · ${esc(a.name)}</option>`).join('')}</select></label><label class="field">หัวข้อ<input name="title" required></label><label class="field">กำหนดวันที่<input name="due" type="date" required></label><label class="field">รอบซ้ำ<input name="repeat"></label><label class="field">เตือนล่วงหน้า (วัน)<input name="lead" type="number" value="30"></label></div>`,fd=>data.reminders.push({id:crypto.randomUUID(),assetId:fd.get('assetId'),title:fd.get('title'),due:fd.get('due'),repeat:fd.get('repeat'),lead:+fd.get('lead'),status:'active'}));window.completeReminder=id=>{const r=data.reminders.find(x=>x.id===id);if(r){r.status='done';save();render()}};
$('addAssignBtn').onclick=()=>generic('มอบหมายผู้ดูแล',`<div class="form-grid"><label class="field">ชื่อผู้รับผิดชอบ<input name="assignee" required></label><label class="field">Role<select name="role"><option>Manager</option><option>Captain</option><option>Staff</option></select></label><label class="field">ขอบเขต<select name="scopeType"><option>รายทรัพย์สิน</option><option>หมวดหมู่</option><option>พื้นที่/แผนก</option><option>ทั้งระดับ/ทั้งกลุ่ม</option><option>ทั้งหมดในขอบเขต</option></select></label><label class="field">รายละเอียดขอบเขต<input name="scope" required></label><label class="field">งานที่มอบหมาย<input name="task" required></label><label class="field">เริ่มวันที่<input name="from" type="date"></label><label class="field">สิ้นสุด<input name="to" type="date"></label></div>`,fd=>data.assignments.push({id:crypto.randomUUID(),assignee:fd.get('assignee'),role:fd.get('role'),scopeType:fd.get('scopeType'),scope:fd.get('scope'),task:fd.get('task'),from:fd.get('from'),to:fd.get('to')}));
render();
